name = "Yau Research Group"
description = "Website for the Christopher Yau Research Group at University of Oxford"
homepage = "http://https://cwcyau.github.io/"
tags = ["academic",
        "university",
        "research",
        "publications"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Christopher Yau"
  homepage = "https://cwcyau.github.io/"
